version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    build:
      context: .
      dockerfile: dockerfiles/rabbitmq.dockerfile
    ports:
      - 15672:15672

  producer:
    container_name: producer
    build:
      context: .
      dockerfile: producer/Dockerfile
    restart: on-failure
    entrypoint: /usr/local/sbin/producer "feed.games" "A new game" #Sends to feed.games topic
    # command: tail -F /dev/null
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq

  consumer_all:
    container_name: consumer
    build:
      context: .
      dockerfile: consumer/Dockerfile
    restart: on-failure
    entrypoint: /usr/local/sbin/consumer "#" # Receive from all topics
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq