version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    build:
      context: .
      dockerfile: dockerfiles/rabbitmq.dockerfile
    ports:
      - 15672:15672

  producer:
    container_name: producer
    build:
      context: .
      dockerfile: producer/Dockerfile
    restart: on-failure
    entrypoint: /usr/local/sbin/producer "feeds_topic" "game.feed" # exchange & routing_key
    # command: tail -F /dev/null
    volumes:
      # - ${PWD}/data/atp-tennis-matches:/data
      - ${PWD}/data/sample:/data
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq

  consumer_all:
    container_name: consumer
    build:
      context: .
      dockerfile: consumer/Dockerfile
    restart: on-failure
    entrypoint: /usr/local/sbin/consumer "game.*" # Receive from all routing keys
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq